### ISSUE TITLE
Uncaught TypeError: 'set' on proxy: trap returned falsish for property '__loaded'

### ISSUE THREAD

**Issue by riazXrazor** [bajankristof/nedb-promises#5]
Hi , i am getting this error 
on using `Datastore.create('/path/to/db.db');` gives this error but `new Datastore(...)` works jst fine.
```JS
I:\Electron\udemy-dl-gui\node_modules\nedb-promises\lib\Datastore.js:30 Uncaught TypeError: 'set' on proxy: trap returned falsish for property '__loaded'
    at __original.loadDatabase (I:\Electron\udemy-dl-gui\node_modules\nedb-promises\lib\Datastore.js:30:19)
    at newArguments.(anonymous function) (I:\Electron\udemy-dl-gui\node_modules\nedb\lib\executor.js:29:17)
    at I:\Electron\udemy-dl-gui\node_modules\nedb\lib\persistence.js:308:15
    at I:\Electron\udemy-dl-gui\node_modules\nedb\lib\persistence.js:140:12
    at I:\Electron\udemy-dl-gui\node_modules\nedb\lib\storage.js:105:30
    at storage.flushToStorage (I:\Electron\udemy-dl-gui\node_modules\nedb\lib\storage.js:56:97)
    at I:\Electron\udemy-dl-gui\node_modules\nedb\node_modules\async\lib\async.js:597:23
    at fn (I:\Electron\udemy-dl-gui\node_modules\nedb\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (I:\Electron\udemy-dl-gui\node_modules\nedb\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by bajankristof** [comment]
Sorry guys for the late reply I am going to investigate this ASAP

**Comment by bajankristof** [comment]
It should be fine now. Check out the fix and see if this issue can be closed or not, and again sorry for the delayed fix...

**Comment by riazXrazor** [comment]
tnx @bajankristof will check it .
